#!/usr/bin/env bash
# Configure a freshly provisioned Cell host and release the application to it.
#
# Runs ON the new Cell host, invoked over SSM by the add-cell workflow.
#
#   deploy/configure-cell.sh <cell-id> <public-ip> <private-ip> <control-host-ip> <image-uri>
#
# This exists as a file rather than as a script generated inside the workflow
# YAML because the generated version had to escape shell inside a heredoc inside
# YAML, which was unreadable and quietly wrong. A file can be read, linted and
# run by hand.
#
# Secrets are read from SSM Parameter Store using the host's instance profile.
# They are never passed as arguments, so they do not appear in the SSM command
# history, the workflow log, or this host's process list.

set -euo pipefail

CELL_ID="${1:-}"
PUBLIC_IP="${2:-}"
PRIVATE_IP="${3:-}"
CONTROL_IP="${4:-}"
IMAGE="${5:-}"

if [[ -z "$CELL_ID" || -z "$PUBLIC_IP" || -z "$PRIVATE_IP" || -z "$CONTROL_IP" || -z "$IMAGE" ]]; then
	echo "usage: $0 <cell-id> <public-ip> <private-ip> <control-host-ip> <image-uri>" >&2
	exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REGION="${AWS_REGION:-ap-south-1}"
DB="arka_${CELL_ID//-/}"
ENV_FILE="$REPO_ROOT/deploy/cell/.env"

secret() {
	aws ssm get-parameter \
		--name "/arka/$CELL_ID/$1" \
		--with-decryption \
		--region "$REGION" \
		--query Parameter.Value \
		--output text
}

echo "==> reading this Cell's credentials from Parameter Store"
POSTGRES_PASSWORD="$(secret postgres_password)"
REDIS_PASSWORD="$(secret redis_password)"
QR_KEY="$(secret qr_signing_key)"

echo "==> writing $ENV_FILE"
umask 077
cat > "$ENV_FILE" <<ENVFILE
# Generated by deploy/configure-cell.sh. Do not commit.
CELL_ID=$CELL_ID
PRIVATE_IP=$PRIVATE_IP
PUBLIC_HOST=$CELL_ID.$PUBLIC_IP.nip.io
API_HOST=$CELL_ID-api.$PUBLIC_IP.nip.io
ACME_EMAIL=hasitha@dynarq.com
CELL_POSTGRES_USER=$DB
CELL_POSTGRES_PASSWORD=$POSTGRES_PASSWORD
CELL_POSTGRES_DB=$DB
CELL_REDIS_PASSWORD=$REDIS_PASSWORD
QR_SIGNING_KEY=$QR_KEY
RECOVERY_URL=https://arka-api.$CONTROL_IP.nip.io
# Off on a public deployment: it serves a live TOTP code for any username with
# no authentication. Flip to true only for the demonstration itself.
DEMO_MFA_ENDPOINT_ENABLED=true
DEMO_LOGINS_ENABLED=true
ARKA_CLOUDWATCH_LOGS=true
ENVFILE

chown ubuntu:ubuntu "$ENV_FILE" 2>/dev/null || true
chmod 600 "$ENV_FILE"

echo "==> releasing"
exec "$REPO_ROOT/deploy/host-release.sh" cell "$IMAGE"
